#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-randomNames
Version  : 1.6.0.0
Release  : 42
URL      : https://cran.r-project.org/src/contrib/randomNames_1.6-0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/randomNames_1.6-0.0.tar.gz
Summary  : Generate Random Given and Surnames
Group    : Development/Tools
License  : GPL-3.0
Requires: R-crayon
Requires: R-data.table
Requires: R-toOrdinal
BuildRequires : R-crayon
BuildRequires : R-data.table
BuildRequires : R-toOrdinal
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%prep
%setup -q -n randomNames
pushd ..
cp -a randomNames buildavx2
popd
pushd ..
cp -a randomNames buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1715021315

%install
export SOURCE_DATE_EPOCH=1715021315
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/randomNames/CITATION
/usr/lib64/R/library/randomNames/DESCRIPTION
/usr/lib64/R/library/randomNames/INDEX
/usr/lib64/R/library/randomNames/Meta/Rd.rds
/usr/lib64/R/library/randomNames/Meta/data.rds
/usr/lib64/R/library/randomNames/Meta/features.rds
/usr/lib64/R/library/randomNames/Meta/hsearch.rds
/usr/lib64/R/library/randomNames/Meta/links.rds
/usr/lib64/R/library/randomNames/Meta/nsInfo.rds
/usr/lib64/R/library/randomNames/Meta/package.rds
/usr/lib64/R/library/randomNames/Meta/vignette.rds
/usr/lib64/R/library/randomNames/NAMESPACE
/usr/lib64/R/library/randomNames/NEWS
/usr/lib64/R/library/randomNames/R/randomNames
/usr/lib64/R/library/randomNames/R/randomNames.rdb
/usr/lib64/R/library/randomNames/R/randomNames.rdx
/usr/lib64/R/library/randomNames/data/Rdata.rdb
/usr/lib64/R/library/randomNames/data/Rdata.rds
/usr/lib64/R/library/randomNames/data/Rdata.rdx
/usr/lib64/R/library/randomNames/data/datalist
/usr/lib64/R/library/randomNames/doc/index.html
/usr/lib64/R/library/randomNames/doc/randomNames.R
/usr/lib64/R/library/randomNames/doc/randomNames.Rmd
/usr/lib64/R/library/randomNames/doc/randomNames.html
/usr/lib64/R/library/randomNames/help/AnIndex
/usr/lib64/R/library/randomNames/help/aliases.rds
/usr/lib64/R/library/randomNames/help/paths.rds
/usr/lib64/R/library/randomNames/help/randomNames.rdb
/usr/lib64/R/library/randomNames/help/randomNames.rdx
/usr/lib64/R/library/randomNames/html/00Index.html
/usr/lib64/R/library/randomNames/html/R.css
